<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logo-icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="LiveCharts" Version="0.9.7" />
    <PackageReference Include="LiveCharts.Core" Version="0.9.8" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes.Wpf" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="NPOI" Version="2.7.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
    <PackageReference Include="PdfSharp-gdi" Version="1.50.5147" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
    <PackageReference Include="System.Net.Http.Json" Version="10.0.3" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.2" />
    <PackageReference Include="Twilio" Version="7.14.1" />
    <PackageReference Include="Zen.Barcode.Core" Version="2.0.0" />
  </ItemGroup>

</Project>
